cp /data/home/zion/deNovo/rawData/count.py ./count1.py
cp /data/home/zion/deNovo/trimmomatic/count.py ./count2.py
cp /data/home/zion/deNovo/seqtk/backup/count.py ./count3.py
cp /data/home/zion/deNovo/seqtk/backup/stat.py ./stat1.py
cp /data/home/zion/deNovo/seqtk/stat.py ./stat2.py
cp /data/home/zion/deNovo/blastn/cmd.py ./cmd.py
cp /data/home/zion/deNovo/blastn/blastn.py ./blastn.py
cp /data/home/zion/test/count.py ./count4.py
cp /data/home/zion/test/stat.py ./stat3.py
cp /data/home/zion/test/test.py ./test.py
cp /data/home/zion/test/sqs.py ./sqs.py
cp /data/home/zion/test/MGcnt.py ./MGcnt.py
cp /data/home/zion/test/merge/modmod.py ./modmod.py
cp /data/home/zion/test/merge/merge.py .
cp /data/home/zion/hamming/hamming.py .
cp /data/home/zion/wgs/test/excel.py ./excel1.py
cp /data/home/zion/wgs/excel_all.py .
cp /data/home/zion/wgs/excel.py ./excel2.py
